version: "3.7"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./backup:/backup
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}

  frontend:
    image: artifacts.microchip.com:7999/microchip/m8a/github-views/frontend:prod
    # build: ./frontend
    ports:
      - 8000:3000
    environment:
      API_HOST: http://backend:8000/
    depends_on:
      - backend

  backend:
    image: artifacts.microchip.com:7999/microchip/m8a/github-views/backend:prod
    build: ./backend
    restart: unless-stopped
    ports:
      - 3000:8000
    depends_on:
      - mongo
    environment:
      PORT: 8000
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      GH_CLIENT_ID: ${GH_CLIENT_ID}
      GH_CLIENT_SECRET: ${GH_CLIENT_SECRET}
      TOKEN_ENC_KEY: ${TOKEN_ENC_KEY}
      TOKEN_SIG_KEY: ${TOKEN_SIG_KEY}
