apiVersion: v1
kind: Pod
metadata:
  name: docker-building-release
spec:
  containers:
    - name: setup
      image: 'alpine/git'
      imagePullPolicy: Always
      command: ['cat']
      tty: true
      resources:
        requests:
          cpu: 200m
          memory: 250Mi
        limits:
          cpu: 250m
          memory: 500Gi
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: Always
      command:
      - /busybox/cat
      tty: true
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1500m
          memory: 2000Mi
    - name: semantic-release
      image: node
      imagePullPolicy: Always
      command:
      - cat
      tty: true