apiVersion: v1
kind: Pod
metadata:
  name: docker-builder
  labels:
    ci.microchip.com/bu: mcu8apps
spec:
  containers:
    - name: setup
      image: 'alpine/git'
      imagePullPolicy: Always
      command: ['cat']
      tty: true
      resources:
        requests:
          cpu: 200m
          memory: 250Mi
        limits:
          cpu: 250m
          memory: 500Mi
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: Always
      command:
      - /busybox/cat
      tty: true
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 2
          memory: 3000Mi